#!/bin/sh

create_session() {
  local name=$1
  local path=$2

  if tmux has-session -t "$name" 2>/dev/null; then
    tmux attach-session -t "$name"
  else
    tmux new-session -s "$name" -c "$path"
  fi
}

# Ensure an argument is provided
if [[ -z "$1" ]]; then
  echo "Error: No command or session name provided."
  echo "Run: tsm help"
  exit 1
fi

case "$1" in

  ws)
    default_dirs=("$HOME/work" "$HOME/programs" "$HOME/learn")

    selddirs=$(
      for dir in "${default_dirs[@]}"; do
        if [[ -d "$dir" ]]; then
          find "$dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null
        fi
      done | fzf
    )
    if [[ -n "$selddirs" ]]; then
      create_session "$(basename "$selddirs")" "$selddirs"
      exit 0
    fi
    ;;

  switch)
    session=$(tmux list-sessions -F '#{session_name}' 2>/dev/null | fzf)
    [[ -n "$session" ]] && tmux switch-client -t "$session"
    ;;

  here)
    create_session "$(basename "$PWD")" "$PWD"
    ;;

  help)
    echo ""
    echo "Tmux Session Manager"
    echo "--------------------"
    echo "Usage:"
    echo "  tsm <session-name>"
    echo "      Create a <session-name> using current directory or if <session-name> exist will attach to that session."
    echo ""
    echo "  tsm here"
    echo "      Create/attach a session using the current directory name."
    echo ""
    echo "  tsm ws"
    echo "      Pick a directory from ~/work or ~/programs and create a session."
    echo ""
    echo "  tsm switch"
    echo "      Switch to an existing tmux session."
    echo ""
    echo "  tsm help"
    echo "      Show this help message."
    echo ""
    ;;

  *)
    create_session "$1" "$PWD"
    ;;
esac
