#!/bin/sh

create_session() {
  local name=$1
  local path=$2

  if tmux has-session -t "$name" 2>/dev/null; then
    tmux attach-session -t "$name"
  else
    tmux new-session -s "$name" -c "$path"
  fi
}

# Ensure an argument is provided
if [[ -z "$1" ]]; then
  echo "Error: No command or session name provided."
  echo "Run: tsm help"
  exit 1
fi

search_dirs=("Learn" "Projects" "Work")

case "$1" in

  ws)
    selected_dir=$(
      for dir in "${search_dirs[@]}"; do
        if [[ -d "$HOME/$dir" ]]; then
          find "$HOME/$dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null
        fi
      done | fzf --delimiter='/' --with-nth='-2..'
    )

    if [[ -n "$selected_dir" ]]; then
      create_session "$(basename "$selected_dir")" "$selected_dir"
      exit 0
    fi
    ;;

  switch)
    session=$(tmux list-sessions -F '#{session_name}' 2>/dev/null | fzf)
    [[ -n "$session" ]] && tmux switch-client -t "$session"
    ;;

  here)
    create_session "$(basename "$PWD")" "$PWD"
    ;;

  help)
    dirstr=""
    for dir in "${search_dirs[@]}"; do
      dirstr+="~/$dir "
    done

    echo "Tmux Session Manager"
    echo ""
    echo "Usage:"
    echo "  tsm <session-name>"
    echo "      Create a <session-name> using current directory or if <session-name> exist will attach to that session."
    echo ""
    echo "  tsm here"
    echo "      Create/attach a session using the current directory name."
    echo ""
    echo "  tsm ws"
    echo "      Pick a directory from $dirstr and create a session."
    echo ""
    echo "  tsm switch"
    echo "      Switch to an existing tmux session."
    echo ""
    echo "  tsm help"
    echo "      Show this help message."
    echo ""
    ;;

  *)
    create_session "$1" "$PWD"
    ;;
esac
