services:
  pg:
    image: postgres:18
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:8.4.0
    environment:
      REDIS_PASSWORD: redispwd
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  pg_data:
  redis_data:

networks:
  dbnet:
    driver: bridge
