set -g mouse on
set -g default-terminal "screen-256color"
set -g base-index 1
set -g status-left-length 50
set -g pane-base-index 1
set -g renumber-windows on
set -g status-justify centre

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf
