#!/bin/sh
#confrimation to overwrite or delete
alias cp='cp -iv'
alias rm='rm -iv'
alias mv='mv -iv'

#color
alias ls='ls --color=auto'
alias la='ls -A'
alias ld='ls -la'
alias grep='grep --color=auto'

# package manager
alias pacc='sudo pacman -R $(pacman -Qtdq)'

# applications
alias fm="yazi"
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
