#!/bin/sh 

# Lang
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# xdg base
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# xdg paths
export XINITRC="$XDG_CONFIG_HOME"/x11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/x11/xserverrc
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export GOPATH="$XDG_DATA_HOME"/go
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export LESSHISTFILE="$XDG_DATA_HOME"/lesshst
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history 
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MINIKUBE_HOME="$XDG_DATA_HOME"/minikube
export KUBECONFIG="$XDG_CONFIG_HOME"/kube 
export KUBECACHEDIR="$XDG_CACHE_HOME"/kube
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"

# sdk
export JAVA_HOME=/usr/lib/jvm/default
export ANDROID_HOME=$XDG_DATA_HOME/Android/Sdk
export ANDROID_SDK_ROOT=$XDG_DATA_HOME/Android/Sdk
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export NVM_DIR=$XDG_DATA_HOME/nvm
export FVM_CACHE_PATH=$XDG_DATA_HOME/fvm

# executables
export PATH=$XDG_DATA_HOME/npm/bin:$PATH
export PATH=$CARGO_HOME/bin:$PATH
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/tools/bin:$PATH
export PATH=$ANDROID_HOME/platforms:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/emulator:$PATH
export PATH=$FVM_CACHE_PATH/default/bin:$PATH
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH":"$XDG_DATA_HOME/.pub-cache/bin"
export PATH="$(find ~/.local/bin/ -type d -printf %p:):$PATH"
eval "$(pyenv init -)"

# default programs
export TERM="xterm-256color"
export COLORTERM="truecolor"
export TERMINAL="alacritty"
export BROWSER="brave"
export EDITOR="nvim"
export VISUAL="nvim"
export READER="zathura"
export PAGER="less -RF"
export VIDEO="mpv"
export IMAGE="nsxiv"
export OPENER="xdg-open"

# programs settings
export FZF_DEFAULT_COMMAND="find ! -path './.cache/*'"
export MOZ_USE_XINPUT2="1"	                # Mozilla smooth scrolling/touchpads.
export QT_QPA_PLATFORMTHEME=qt5ct           # Theme for qt apps
# export QT_QPA_PLATFORMTHEME=gtk2            # qt app to follow gtk2 theme

# flutter chrome 
export CHROME_EXECUTABLE="/usr/bin/chromium"

# source bashrc when login to bash
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
