#!/bin/sh

while read file
do
    case "$1" in
        "y")
            echo -n "$file" | tr -d '\n' | xclip -selection clipboard && 
                notify-send "$file copied to clipboard" ;;
        "Y")
            readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" ;;
        "w") 
            cp "$file" ~/.config/wall && xwallpaper --stretch ~/.config/wall ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "t")
            trash-put "$file" ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "i")	
            notify-send "File information" "$(mediainfo "$file")" ;;
        *)
            notify-send -t 5 "Invalid key-handler $1" ;;
    esac
done
